language: generic
matrix:
  include:
    - env: GFORTRAN_VERSION=6 OPT=FAST
      sudo: required
      dist: trusty
      os: linux
    - os: osx
      env: OPT=FAST
before_install:
  - uname
  - export TRAVIS_ROOT=$HOME/local
  - mkdir -p $TRAVIS_ROOT/bin
  - mkdir $HOME/.gdrive
  - openssl aes-256-cbc -K $encrypted_f41f697aab60_key -iv $encrypted_f41f697aab60_iv -in token_v2.json.enc -out $HOME/.gdrive/token_v2.json -d

install:
  - echo "$TRAVIS_OS_NAME";
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "On OSX";
      wget "https://docs.google.com/uc?id=0B3X9GlR6Embnb010SnpUV0s2ZkU&export=download" -O gdrive;
      chmod +x ./gdrive;
      ./TRAVIS/install_brews.sh;
    else
      echo "On LINUX";
      wget "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download" -O gdrive;
      chmod +x ./gdrive;
      if [[ "$GFORTRAN_VERSION" == "trusty" ]]; then 
        sudo apt-get update -qq;
        sudo apt-get install -qq gfortran libnetcdff5 libnetcdf-dev libfftw3-dev openmpi-bin libopenmpi-dev;
      else
        sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test";
        sudo -E apt-get -yq update;
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gfortran-$GFORTRAN_VERSION g++-$GFORTRAN_VERSION;
      fi
    fi
script:
  - ./gdrive list
    #- ./gdrive download 0B2O7p0iBm8A9SWk1WjJZUDR5dVU
  - echo $COMPILER $GFORTRAN_VERSION
after_script:
after_success: 
cache:
  apt: true
  directories:
  - $HOME/travis
  - $HOME/Library/Caches/Homebrew
  - /usr/local/Cellar/
