language: generic

# Use the trusty environment, since the netcdf packages in 12.04 are broken
dist: trusty
sudo: required

env:
  - GFORTRAN_VERSION=4.8 MPI_IMPL=openmpi
  - GFORTRAN_VERSION=4.9 MPI_IMPL=openmpi
  - GFORTRAN_VERSION=5 MPI_IMPL=openmpi
  - GFORTRAN_VERSION=6 MPI_IMPL=openmpi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-4.8
      - gfortran-4.9
      - gfortran-5
      - gfortran-6

before_install:
  # Get OpenMPI
- ./install_mpi.sh $TRAVIS_ROOT $MPI_IMPL 

install:
- gfortran-$GFORTRAN_VERSION -v
- gfortran-$GFORTRAN_VERSION hello_world.f90 -o hello_world.x

script:
- ./hello_world.x

after_success:

cache:
  directories:
    - $HOME/miniconda
