language: generic
dist: trusty
sudo: required
env:
  - GFORTRAN_VERSION=4.8
before_install:
  - mkdir $HOME/.gdrive
  - openssl aes-256-cbc -K $encrypted_f41f697aab60_key -iv $encrypted_f41f697aab60_iv -in token_v2.json.enc -out $HOME/.gdrive/token_v2.json -d
install:
  - wget "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download" -O gdrive
  - chmod +x ./gdrive
script:
  - ./gdrive list
  - echo $COMPILER $GFORTRAN_VERSION
after_script:
after_success: 
cache:
  apt: true
  directories:
  - $HOME/travis
