language: generic
dist: trusty
sudo: required
env:
  - COMPILER=gcc
  - COMPILER=icc
  - GFORTRAN_VERSION=4.8
  - GFORTRAN_VERSION=4.9
before_install:
  #- export TRAVIS_ROOT=$HOME/travis
  #- mkdir -p $TRAVIS_ROOT
  #- ./TRAVIS/install_compiler.sh $TRAVIS_ROOT $COMPILER $GFORTRAN_VERSION
  #- ./TRAVIS/install_mpi.sh $TRAVIS_ROOT $MPI_IMPL $COMPILER $GFORTRAN_VERSION
  #- ./TRAVIS/install_fftw.sh $TRAVIS_ROOT $COMPILER $GFORTRAN_VERSION
  #- ./TRAVIS/install_netcdf.sh $TRAVIS_ROOT $COMPILER $GFORTRAN_VERSION
install:

  #- $FC -v
  #- $FC hello_world.f90 -o hello_world.x
script:
- echo $COMPILER $GFORTRAN_VERSION
after_script:
    - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
after_success: 
cache:
  apt: true
  directories:
  - $HOME/travis
